from pydantic import BaseModel
from typing import List, Dict, Any, Optional

class ChatRequest(BaseModel):
    dataset_id: int
    question: str
    use_cache: bool = True  # 是否使用缓存，默认启用
    conversation_history: Optional[List[Dict[str, str]]] = None  # 对话历史，用于上下文理解
    data_table_id: Optional[int] = None  # 数据表ID，如果指定则只查询该表

class ChatResponse(BaseModel):
    sql: Optional[str] = None
    columns: Optional[List[str]] = None
    rows: Optional[List[Dict[str, Any]]] = None
    chart_type: str
    summary: Optional[str] = None
    answer_text: Optional[str] = None  # For clarification requests
    steps: Optional[List[str]] = None  # Execution steps tracking
    from_cache: Optional[bool] = False  # Whether result is from cache (deprecated, use is_cached)
    is_cached: Optional[bool] = False  # Whether result is from cache
    insight: Optional[str] = None  # Business analysis insight generated by AI analyst agent
    alternative_charts: Optional[List[str]] = None  # Alternative chart types for switching
    data_interpretation: Optional['DataInterpretation'] = None  # 数据解读
    fluctuation_analysis: Optional['FluctuationAnalysis'] = None  # 波动归因
    followup_questions: Optional[List[str]] = None  # 后续推荐问题

class SummaryRequest(BaseModel):
    dataset_id: int
    question: str
    sql: str
    columns: List[str]
    rows: List[Dict[str, Any]]

class SummaryResponse(BaseModel):
    summary: str

class FeedbackRequest(BaseModel):
    dataset_id: int
    question: str
    sql: str  # For rating=1 (like): original SQL; For rating=-1 (dislike): corrected SQL
    rating: int  # 1 for like, -1 for dislike

class FeedbackResponse(BaseModel):
    success: bool
    message: str

# ============ 输入联想相关 Schema ============

class InputSuggestRequest(BaseModel):
    dataset_id: int
    partial_input: str
    limit: int = 5

class InputSuggestResponse(BaseModel):
    suggestions: List[str]

# ============ 数据解读相关 Schema ============

class DataInterpretation(BaseModel):
    summary: str
    key_findings: List[str]
    statistics: Dict[str, Any]
    quality_score: Optional[int] = None

# ============ 波动归因相关 Schema ============

class FluctuationAnalysis(BaseModel):
    has_fluctuation: bool
    fluctuation_points: Optional[List[Dict]] = None
    attribution: Optional[Dict[str, Any]] = None
    chart_recommendation: Optional[str] = None

# ============ 后续问题推荐 Schema ============

class FollowupSuggestRequest(BaseModel):
    dataset_id: int
    current_question: str
    current_result: Dict[str, Any]
    limit: int = 3

class FollowupSuggestResponse(BaseModel):
    followup_questions: List[str]

# ============ 导出相关 Schema ============

class ExportRequest(BaseModel):
    question: str
    sql: Optional[str] = None
    columns: List[str]
    rows: List[Dict[str, Any]]
    chart_type: str
    chart_data: Optional[Dict] = None
    insight: Optional[str] = None
    data_interpretation: Optional[DataInterpretation] = None
    fluctuation_analysis: Optional[FluctuationAnalysis] = None
    format: str  # "excel" | "excel_with_chart" | "pdf" | "csv"
