from pydantic import BaseModel
from typing import List, Dict, Any, Optional

class ChatRequest(BaseModel):
    dataset_id: int
    question: str
    use_cache: bool = True  # 是否使用缓存，默认启用
    conversation_history: Optional[List[Dict[str, str]]] = None  # 对话历史，用于上下文理解

class ChatResponse(BaseModel):
    sql: Optional[str] = None
    columns: Optional[List[str]] = None
    rows: Optional[List[Dict[str, Any]]] = None
    chart_type: str
    summary: Optional[str] = None
    answer_text: Optional[str] = None  # For clarification requests
    steps: Optional[List[str]] = None  # Execution steps tracking
    from_cache: Optional[bool] = False  # Whether result is from cache (deprecated, use is_cached)
    is_cached: Optional[bool] = False  # Whether result is from cache
    insight: Optional[str] = None  # Business analysis insight generated by AI analyst agent
    alternative_charts: Optional[List[str]] = None  # Alternative chart types for switching
    next_questions: Optional[List[str]] = None  # Suggested follow-up questions

class SummaryRequest(BaseModel):
    dataset_id: int
    question: str
    sql: str
    columns: List[str]
    rows: List[Dict[str, Any]]

class SummaryResponse(BaseModel):
    summary: str

class FeedbackRequest(BaseModel):
    dataset_id: int
    question: str
    sql: str  # For rating=1 (like): original SQL; For rating=-1 (dislike): corrected SQL
    rating: int  # 1 for like, -1 for dislike

class FeedbackResponse(BaseModel):
    success: bool
    message: str
